### ISSUE TITLE
Problems with Unicode characters

### ISSUE THREAD

**Issue by sharkdp** [FrigoEU/psc-ide-vim#15]
Not sure if this is a problem of `psc-ide-vim`, of `psc-ide` (/cc @kRITZCREEK) or if it is due to user error :smile: ..

I start with the following file:

``` purs
module TestUnicode where

id :: ∀ a. a → a
id x = x

test :: String
test = show "asd"
```

Then I run `:PSCIDEimportIdentifier` with the cursor on `show`. The import statement is correctly added, but the Unicode symbols get messed up:

``` purs
module TestUnicode where

import Prelude (show)

id :: â a. a â a
id x = x

test :: String
test = show "asd"
```

(By the way, both psc-ide-vim and psc-ide are fantastic!!)

**Comment by FrigoEU** [comment]
Hmm this feels like something psc-ide is doing, or something weird in how psc-ide and vim interact. Let's see if @kRITZCREEK can shed some light on this.

**Comment by kritzcreek** [comment]
We had problems with unicode in an earlier version of `psc-ide`, but that should've been fixed with https://github.com/purescript/purescript/commit/fea78a9401af0969e4f2b82aa474fde8fa080483. If you're using PS >= 0.8.5 that fix should already be applied... I'll try to repo later

**Comment by sharkdp** [comment]
I'm using the current version 0.9.1

**Comment by kritzcreek** [comment]
![](https://media.giphy.com/media/l41Y9VxH9abpL4kKs/giphy.gif)

I think `psc-ide`assumes UTF-8, maybe your file has a different encoding?

**Comment by sharkdp** [comment]
Thanks for the feedback.

That's strange. The file encoding is definitely UTF-8:

```
$ file src/Main.purs 
src/Main.purs: UTF-8 Unicode text
```

That's also what vim shows. I thought it might have something to do with my vim config, so I reduced my .vimrc to this:

``` Vim
" vim instead of vi settings
set nocompatible

" Vundle
filetype off  " required to load Vundle

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'raichoo/purescript-vim'
Plugin 'frigoeu/psc-ide-vim'

call vundle#end()

" default encoding in UTF-8
filetype plugin indent on
set encoding=utf-8
```

But the problem persists... :frowning: 

(What screen-grabber do you use? :smile:)

**Comment by oblitum** [comment]
I got more WTF with that moving rainbow 😄

**Comment by oblitum** [comment]
For what's worth, I reproduce the same.

**Comment by kritzcreek** [comment]
1. @oblitum that's [nyan cat](https://www.emacswiki.org/emacs/NyanMode) ;) 
2. @sharkdp The screen grabber is Giphy (only use it on the mac though)
3. How about you start a `psc-ide-server --debug` instance in the terminal, and talk to it via `psc-ide-client` on the command line. 

This is what the command looks like (you'll have to put it into a single line and change the paths):

``` js
{
  "command": "import",
  "params": {
    "file": "/home/creek/Documents/chromacannon/src/Demo.purs",
    "outfile": "/home/creek/Documents/chromacannon/src/Demo.purs",
    "importCommand": {
      "importCommand": "addImport",
      "identifier": "show"
    } 
  }
} 
```

EDIT: Make sure you send a load command before trying the import command.

``` js
{"command":"load"}
```

**Comment by sharkdp** [comment]
I didn't manage to send the commands to psc-ide-client directly. Do I need to pass some parameters to the `"load"` command? Or be in some specific directory?

I did, however, enable debugging in psc-ide-vim and is created this output:

```
ident: show
s:tempfile: /tmp/vCAM4IO/1
callPscIde: start: Executing command: {'params': {'file': '/tmp/vCAM4IO/1', 'importCommand': {'importCommand': 'addImport', 'identifier': 'show'}}, 'command': 'import'}
callPscIde: Raw response: {"result":[{"identifier":"show","module":"Data.Show","type":"forall a. (Show a) => a -> String"},{"identifier":"show","module":"Prelude","type":"forall a. (Show a) => a -> String"}],"resu
ltType":"success"}^@
callPscIde: Decoded response: {'result': [{'module': 'Data.Show', 'identifier': 'show', 'type': 'forall a. (Show a) => a -> String'}, {'module': 'Prelude', 'identifier': 'show', 'type': 'forall a. (Show a) => a ->
 String'}], 'resultType': 'success'}
Multiple possibilities to import show

PSCIDEimportIdentifier
ident: show
s:tempfile: /tmp/vCAM4IO/1
callPscIde: start: Executing command: {'params': {'file': '/tmp/vCAM4IO/1', 'importCommand': {'importCommand': 'addImport', 'identifier': 'show'}, 'filters': [{'filter': 'modules', 'params': {'modules': ['Data.Sho
w']}}]}, 'command': 'import'}
callPscIde: Raw response: {"result":["module TestUnicode where","","import Data.Show (show)","","id :: â<88><80> a. a â<86><92> a","id x = x","","test :: String","test = show \"asd\""],"resultType":"success"}^@
callPscIde: Decoded response: {'result': ['module TestUnicode where', '', 'import Data.Show (show)', '', 'id :: â<88><80> a. a â<86><92> a', 'id x = x', '', 'test :: String', 'test = show "asd"'], 'resultType': 's
uccess'}
linesdiff: 2
nrOfOldlinesUnderLine: 6
nrOfNewlinesUnderLine: 8
nrOfLinesToReplace: 6
nrOfLinesToDelete: 0
nrOfLinesToAppend: 2
linesToAppend: ['', 'test :: String']
PSCIDEimportIdentifier: Succesfully imported identifier: Data.Show show
```

Note that the second "callPscIde: Raw response" includes the scrambled symbols. The created tempfile looks fine (including utf-8 encoding) ...

**Comment by kritzcreek** [comment]
Oh allright I think only the vim plugin is using the response from the json instead of the outfile. Might be an encoding issue around that then. Thanks I'll try to reproduce and fix it tomorrow.

**Comment by oblitum** [comment]
I've got this on the command line:

``` vim
❯❯❯ psc-ide-client -p 4242
{"params": {"file": "/tmp/francisco/v8hpznD/3", "importCommand": {"importCommand": "addImport", "identifier": "show"}, "filters": [{"filter": "modules", "params": {"modules": ["Data.Show"]}}]}, "command": "import"}
{"result":["module TestUnicode where","","import Data.Show (show)","","id :: â a. a â a","id x = x","","test :: String","test = show \"asd\""],"resultType":"success"}
```

**Comment by oblitum** [comment]
By the way, I've grabbed the command from the plugin instead of trying your suggestion. My temp file was:

``` purescript
module TestUnicode where

id :: ∀ a. a → a
id x = x

test :: String
test = show "asd"
```

**Comment by oblitum** [comment]
@sharkdp I got a bit of time to figure out you need to press enter after `psc-ide-client -p 4242`, and then insert the command, json encoded.

**Comment by oblitum** [comment]
by https://github.com/FrigoEU/psc-ide-vim/issues/15#issuecomment-230922515, it's definitely a psc-ide issue.

**Comment by kritzcreek** [comment]
If someone's got a haskell environment set up, could you compile and try out my fix? https://github.com/purescript/purescript/pull/2221 It works for me, but I don't have a VIM installation to test if it's fixed in the editor aswell.

**Comment by sharkdp** [comment]
Sorry.. I didn't see your pull requests. Just tried it and it works perfectly!

I guess we can leave this open until your PR is merged.

**Comment by kritzcreek** [comment]
awesome, thanks for confirming!

**Comment by kritzcreek** [comment]
let's close this when 0.9.2 is released.

**Comment by FrigoEU** [comment]
<3 kritzcreek.

**Comment by FrigoEU** [comment]
Thanks for fixing this @kRITZCREEK ! https://github.com/purescript/purescript/pull/2221
